### ISSUE TITLE
"Server" mode?

### ISSUE THREAD

**Issue by rhizomic** [tstat/tmp-postgres#1]
Hi Travis, thanks so much for your work on this project!

I'm looking into using this as an alternative to the (sadly broken and abandoned) [https://github.com/jfischoff/tmp-postgres](tmp-postgres) project. Is it possible to run an instance indefinitely, such that it can be accessed by other clients? I can "hack" it with `--psql`, but I was wondering if there's a more blessed approach.

**Comment by rhizomic** [comment]
I spent a little more time with this and realized that running _without_ `--psql` does exactly what I want, e.g.:

```
nix run "github:tstat/tmp-postgres" -- /tmp/whatever
```

Sorry for the issue spam! Closing.

**Comment by tstat** [comment]
no problem, glad you sorted itout
